/**
 * Writes narrower WebP copies of every bundled photograph.
 *
 *   npm run responsive          # only what is missing
 *   npm run responsive -- --force
 *
 * A product page currently sends the same 900px JPEG to a 6-inch phone and a
 * 27-inch monitor. On a phone that is roughly six times the pixels the screen
 * can show and six times the bytes the visitor pays for — and on a slow
 * connection it is the difference between a page that loads and one that gets
 * abandoned. It is also the cheapest performance work available here, because
 * the source files and the encoder are already in the repo.
 *
 * The derivatives are committed rather than generated at deploy time. A theme
 * that only looks right after someone remembers to run a script is a theme that
 * will be seen looking wrong.
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const IMAGES = path.join(ROOT, 'public/images')
const FORCE = process.argv.includes('--force')

/**
 * Two extra widths, not five.
 *
 * 400 covers a phone at 2× and a card in a desktop grid; 900 is the source
 * width, and as WebP it is smaller than the JPEG it replaces, so it earns its
 * place for everyone rather than only for small screens. More breakpoints past
 * that trade real repository weight for a saving nobody perceives.
 */
const WIDTHS = [400, 900]

/** Everything under these is photography. `brand.mjs` owns the rest. */
const DIRECTORIES = ['products', 'categories', 'collections', 'editorial']

const manifest = {}

async function main() {
  let written = 0
  let kept = 0

  for (const dir of DIRECTORIES) {
    const from = path.join(IMAGES, dir)
    let entries = []
    try {
      entries = await fs.readdir(from)
    } catch {
      continue
    }

    for (const file of entries.filter((f) => f.endsWith('.jpg'))) {
      const base = file.replace(/\.jpg$/, '')
      const source = path.join(from, file)
      const { width: sourceWidth } = await sharp(source).metadata()
      const widths = WIDTHS.filter((w) => w <= sourceWidth)
      manifest[`/images/${dir}/${base}.jpg`] = widths

      for (const width of widths) {
        const out = path.join(from, `${base}-${width}.webp`)
        if (!FORCE && (await exists(out))) {
          kept += 1
          continue
        }
        await sharp(source)
          .resize(width, null, { withoutEnlargement: true })
          // 78 is where WebP stops being visibly better and starts being
          // bigger. Verified by eye on the knitwear, which is the hardest
          // texture in this catalogue to compress.
          .webp({ quality: 78, effort: 5 })
          .toFile(out)
        written += 1
      }
    }
  }

  /**
   * A module, not JSON.
   *
   * Node requires `with { type: 'json' }` on a JSON import and Vite does not,
   * so a `.json` manifest works in the browser build and throws in the tests
   * and the prerenderer. A generated `.js` file needs no attribute anywhere.
   */
  const header = [
    '// Generated by scripts/responsive.mjs — do not edit.',
    '//',
    '// Which narrower copies exist for each bundled photograph. Driven by a',
    '// manifest rather than by guessing at filenames, because a srcset candidate',
    '// that 404s is worse than no srcset at all.',
    '',
  ].join('\n')
  await fs.writeFile(
    path.join(ROOT, 'src/data/responsive.js'),
    `${header}export default ${JSON.stringify(manifest, null, 2)}\n`,
  )

  const total = await weigh()
  console.log(
    `[responsive] ${written} written, ${kept} already present · ${Object.keys(manifest).length} sources · ${total}`,
  )
}

const exists = (file) => fs.stat(file).then(() => true, () => false)

async function weigh() {
  let bytes = 0
  for (const dir of DIRECTORIES) {
    const from = path.join(IMAGES, dir)
    const entries = await fs.readdir(from).catch(() => [])
    for (const file of entries.filter((f) => f.endsWith('.webp'))) {
      bytes += (await fs.stat(path.join(from, file))).size
    }
  }
  return `${(bytes / 1024 / 1024).toFixed(1)}MB of derivatives`
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
